packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react18:
    react: ^18.0.0
    react-dom: ^18.0.0
    react-router-dom: ^7.0.0
    lucide-react: ^0.468.0
    react-select: ^5.0.0
    react-hook-form: ^7.0.0
    "@types/react-select": ^5.0.0
    "@types/react": ^18.0.0
    "@types/react-dom": ^18.0.0
    "@types/react-router-dom": ^5.0.0
    react-query: ^3.39.0

  next15:
    next: ^15.0.0

  eslint:
    eslint: ^8.0.0
    "@eslint/js": ^8.0.0
    eslint-plugin-react-hooks: ^5.0.0
    eslint-plugin-react-refresh: ^0.4.0

  tailwindcss:
    tailwindcss: ^3.0.0
    autoprefixer: ^10.0.0
    postcss: ^8.0.0

  typescript:
    typescript: ^5.0.0

  node-types:
    "@types/node": ^20.0.0

  prettier:
    prettier: ^3.0.0

  zod:
    zod: ^3.0.0
